### ISSUE TITLE
Create Health Summary Dashboard

### ISSUE THREAD

**Issue by BjarneS28** [phpngn/UCSD-CSE-118-218-Team-H#24]
Wanted Features:
- /api/emergency - elderly say they need help to alexa and display it
- /api/noticifation ../all show current notifications and if one is due right now
- Ability to check off the notifications (not sure about this)
- Maybe some graphics/diagrams and displaying maximum / average heart rate data

**Comment by allesklardy** [comment]
@GedeonLenz these are some of your tasks
