### ISSUE TITLE
Research and decide on data synchronization between smartwatch and server

### ISSUE THREAD

**Issue by BjarneS28** [phpngn/UCSD-CSE-118-218-Team-H#9]
Find a solution how to synchronize between watch and server (continuous through socket, stream, batch synchronization, call endpoint every x seconds, etc). Briefly document different possible solutions and their advantages/disadvantages. Decide and communicate decision.

Please keep me @BjarneS28 updated on this!

**Comment by allesklardy** [comment]
LGTM
